[package]
name = "nray"
version = "0.1.0"
authors = ["Nikolay Dionisov <nikolaydionisov@gmail.com>"]


[dependencies]
cgmath = "0.12.0"
sdl2 = "0.5.0"
rand = "0.3.0"
time = "0.1"
collision = "0.9.0"
rayon = "0.5.0"